version: '3.4'

services:
  charactersheeter:
    image: charactersheeter
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5000"]
    ports:
      - 5000:5000
      - 5678:5678
    environment:
      - FLASK_APP=app.py
      - SQLALCHEMY_DATABASE_URI=postgres://postgres:postgres@db/debug_db
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - debug_pg_data:/var/lib/postgresql/data

volumes:
  debug_pg_data:
